service: ptolomeo

provider: 
  name: aws
  stage: dev
  region: eu-west-1
  memorySize: 256
  deploymentBucket:
    name: ptolomeo.tfg.marsofon
  plugins:
   - serverless-python-requirements

functions: 
  weather:
    handler: lmbda/weather/app.handler
    name: ptolomeo-weather
    description: Ptolomeo Weather Logic
    runtime: python3.6
    memorySize: 128
    timeout: 30
    events:
    - http:
        path: weather/
        method: post
        integration: lambda
        authorizer: authorization

  authorization:
    handler: lmbda/authorizer/index.handler
    name: ptolomeo-authorizer
    description: Ptolomeo Authorization Logic
    runtime: nodejs8.10
    memorySize: 128
    timeout: 60
